return {
  "williamboman/mason.nvim",
  cmd = "Mason",
  opts = {
    ensure_installed = {
      "marksman",
      "gopls",
      "vtsls",
      "ruff-lsp",
      "pyright",
      "tailwindcss-language-server",
      "rust-analyzer",
      "bash-language-server",
      "clangd",
      "debugpy",
      "delve",
      "eslint-lsp",
      "go-debug-adapter",
      "golangci-lint",
      "golangci-lint-langserver",
      "js-debug-adapter",
      "chrome-debug-adapter",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint",
      "prettier",
      "shellcheck",
      "shfmt",
      "stylua",
      "taplo",
      "typescript-language-server",
    },
  },
}
